// The launchers, and the one rule they have to keep.
//
// Its own module because it is the piece an upgrade breaks if it is wrong, and it is
// only two lines of shell — small enough to be worth proving rather than reading.
// The installer writes them; a hook repairs them, for the reason on
// {@link repairLaunchers}.

import { chmodSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import { HOME, PLUGIN_CACHE } from './paths.mjs'
import { APP_ROOT, isPluginCopy } from './version.mjs'

/**
 * The two things that have to keep working across an upgrade, and where they live.
 *
 * The command, because the plugin's own bin/ is only on PATH inside Claude Code's
 * Bash tool; and the status line, because a plugin's own settings.json cannot set
 * it. Both are named in the user's settings or PATH, so neither can move.
 */
export const LAUNCHERS = [
  { path: join(homedir(), '.local', 'bin', 'claudemon'), target: 'bin/claudemon' },
  { path: join(HOME, 'statusline.sh'), target: 'scripts/run.sh', args: 'statusline.mjs' },
]

/** How a launcher says we wrote it. Nothing without this line is ever touched. */
const MARKER = "Generated by claudemon's installer"

/** The directory a launcher names outright, or nothing if it resolves one instead. */
const NAMED = /^app="(.+)"$/m

/**
 * A launcher that hands over to wherever claudemon currently lives.
 *
 * Installing the plugin copies it to a directory with the version in the path, so a
 * launcher that names one is only right until the next release — and the two things
 * here cannot be rewritten by hand when that happens, because one is on a PATH and
 * the other is named in settings.json.
 *
 * So the named path is not a decision made once at install time: it is maintained.
 * Whatever runs from the newest copy puts its own path in here — the installer when
 * you update from inside the game, and a hook otherwise, since hooks are the only
 * part of claudemon that Claude Code runs from the copy it just installed rather
 * than through one of these. See {@link relinkLaunchers}.
 *
 * The second line is what is left when nothing has done that yet, and it is a guess:
 * newest by modification time, because `sort -V` is not portable and version order
 * cannot be had in POSIX sh. It is a guess worth having as a last resort and not
 * worth relying on — a copy laid down with its timestamps preserved is older than the
 * release before it, and this would pick the wrong one. Being maintained is what
 * makes that a fallback rather than the mechanism.
 *
 * @param {{target: string, args?: string, root: string, cache?: string}} options
 *   `target` is the path within claudemon to hand over to, and `root` is the copy
 *   being named — normally the one calling this.
 */
export function shimSource({ target, args = '', root, cache = PLUGIN_CACHE }) {
  return `#!/bin/sh
# ${MARKER} — rerun it rather than editing this.
#
# Resolves where claudemon lives, then hands over. See src/shim.mjs.

app="${root}"
[ -d "$app" ] || app=$(ls -td "${cache}"/*/ 2>/dev/null | head -1)

if [ -z "$app" ] || [ ! -d "$app" ]; then
  echo "claudemon: cannot find its files. Reinstall with /claudemon-setup" >&2
  exit 1
fi

exec "$app/${target}"${args ? ` ${args}` : ''} "$@"
`
}

/** Writes an executable launcher, creating its directory. */
export function writeLauncher({ path, target, args, root, cache = PLUGIN_CACHE }) {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, shimSource({ target, args, root, cache }))
  chmodSync(path, 0o755)
}

/**
 * Whether a launcher of ours is pointing somewhere other than `root`.
 *
 * The middle case is the one that matters: a launcher naming a path *outside* the
 * plugin cache is naming a clone, and a clone is meant to win — that is the whole
 * development workflow. It is left exactly as it is, however out of date the copy
 * calling this thinks it is.
 */
export function pointsElsewhere(source, root, cache = PLUGIN_CACHE) {
  if (!source.includes(MARKER)) return false

  const named = source.match(NAMED)?.[1]
  if (named == null) return true
  if (!isPluginCopy(named, cache)) return false
  return named !== root
}

/**
 * Points every launcher of ours at `root`, if it is not there already.
 *
 * The upgrade that cannot be done by the thing being upgraded. Until 0.6.0 nothing
 * ever revisited what the installer wrote, so for anyone who installed the plugin
 * rather than cloning it the `claudemon` command went on starting the release that
 * installed it — in silence, the only symptom being a game that never changes.
 *
 * A hook is the one place that can put it right, because hooks are the only part of
 * this that Claude Code runs from the copy it just installed rather than through a
 * launcher. So the first prompt after the restart quietly brings them up to date.
 *
 * Idempotent: the second call finds them already pointing here.
 *
 * @returns {string[]} the launchers rewritten, which is empty almost every time.
 */
export function relinkLaunchers({
  root = APP_ROOT,
  cache = PLUGIN_CACHE,
  launchers = LAUNCHERS,
} = {}) {
  const rewritten = []

  for (const launcher of launchers) {
    let source
    try {
      source = readFileSync(launcher.path, 'utf8')
    } catch {
      // Not installed, or not readable. Either way there is nothing to bring up to
      // date — writing one here would put a command on somebody's PATH uninvited.
      continue
    }

    if (!pointsElsewhere(source, root, cache)) continue

    writeLauncher({ ...launcher, root, cache })
    rewritten.push(launcher.path)
  }

  return rewritten
}
